import type { ChecklistItem, LibraryEntry, Template } from './types'

// Seeded from the user's existing training program. Editable in-app afterward
// via Plans / Library — this is only the first-run default.

export const DEFAULT_TEMPLATES: Template[] = [
  {
    id: 't1',
    name: 'Session 1 — Squat / Push',
    exercises: [
      { id: 'e1', name: 'Squat', target: '3 x 5', desc: 'Back, front, or hack squat — whichever allows most depth and load.', video: '' },
      { id: 'e2', name: 'Single Leg — Leg Press', target: '3 x 6 ES', desc: 'ES = each side. Control the eccentric.', video: '' },
      { id: 'e3', name: 'RDL', target: '3 x 5', desc: 'Hinge at hips, slight knee bend, bar close to legs.', video: '' },
      { id: 'e4', name: 'Bench Press', target: '3 x 5', desc: '', video: '' },
      { id: 'e5', name: 'Seated Cable Row', target: '3 x 8', desc: '', video: '' },
      { id: 'e6', name: 'EZ Bar Bicep Curl', target: '4 x 8', desc: '0 RIR — train to failure on last set.', video: '' },
      { id: 'e7', name: 'Cable Tricep Pushdown', target: '3 x 12', desc: 'Straight bar attachment. 0 RIR.', video: '' },
    ],
  },
  {
    id: 't2',
    name: 'Session 2 — Deadlift / Pull',
    exercises: [
      { id: 'e8', name: 'Deadlift', target: '3 x 5', desc: 'Straight bar or hex bar, whichever allows more load.', video: '' },
      { id: 'e9', name: 'Single Leg — Leg Press', target: '3 x 6 ES', desc: 'ES = each side.', video: '' },
      { id: 'e10', name: 'Prone/Seated Hamstring Curl', target: '3 x 8', desc: '', video: '' },
      { id: 'e11', name: 'Cable Ab Curls', target: '2 x 15', desc: '0 RIR.', video: 'https://www.youtube.com/watch?v=ToJeyhydUxU' },
      { id: 'e12', name: 'Overhead Press', target: '3 x 8', desc: '', video: '' },
      { id: 'e13', name: 'Lat Pulldown', target: '3 x 12', desc: '', video: '' },
      { id: 'e14', name: 'EZ Bar Bicep Curl', target: '4 x 8', desc: '0 RIR.', video: '' },
      { id: 'e15', name: 'Cable Tricep Pushdown', target: '3 x 12', desc: '0 RIR.', video: '' },
    ],
  },
]

export const DEFAULT_LIBRARY: LibraryEntry[] = [
  { id: 'lib1', name: 'Squat', video: 'https://www.youtube.com/watch?v=8060FZiT5TA', desc: 'Back, front, or hack squat — whichever allows most depth and load.' },
  { id: 'lib2', name: 'Deadlift', video: 'https://www.youtube.com/watch?v=VL5Ab0T07e4', desc: 'Conventional deadlift technique breakdown.' },
  { id: 'lib3', name: 'RDL', video: 'https://www.youtube.com/watch?v=_oyxCn2iSjU', desc: 'Hip hinge, slight knee bend, bar close to the legs.' },
  { id: 'lib4', name: 'Bench Press', video: 'https://www.youtube.com/watch?v=vcBig73ojpE', desc: '' },
  { id: 'lib5', name: 'Overhead Press', video: 'https://www.youtube.com/watch?v=Gu1t7X2yq4M', desc: '' },
  { id: 'lib6', name: 'Pull-Ups', video: 'https://www.youtube.com/watch?v=sIvJTfGxdFo', desc: 'Full checklist to avoid the most common mistakes.' },
  { id: 'lib7', name: 'Cable Ab Crunch', video: 'https://www.youtube.com/watch?v=ToJeyhydUxU', desc: 'Kneel facing cable stack, crunch down through the abs, not the hips.' },
  { id: 'lib8', name: 'Split Stance Rot Med Ball Throw', video: 'https://www.youtube.com/watch?v=q66AMNizI0o', desc: 'Rotational power throw, split stance.' },
  { id: 'lib9', name: 'Pogo Hops', video: 'https://www.youtube.com/watch?v=lz6BM6WyJ0k', desc: 'Stiff ankle bounces at target cadence (160 BPM).' },
  { id: 'lib10', name: 'Repeated Broad Jumps', video: 'https://www.youtube.com/watch?v=OLYMM-jK4K8&t=3s', desc: '3 continuous jumps for max distance.' },
  { id: 'lib11', name: 'Cable Hip Flexor March', video: 'https://youtu.be/vyWX2ucEsdw', desc: '' },
  { id: 'lib12', name: 'Front Foot Elevated Pogo Hops', video: 'https://www.youtube.com/watch?v=DNVYrrx9IsA', desc: '' },
  { id: 'lib13', name: 'Single Leg Bounding', video: 'https://youtu.be/b3124L0KK3Q', desc: 'Max distance per bound, each side.' },
  { id: 'lib14', name: 'Single Leg — Leg Press', video: '', desc: 'ES = each side.' },
  { id: 'lib15', name: 'Seated Cable Row', video: '', desc: '' },
  { id: 'lib16', name: 'Lat Pulldown', video: '', desc: '' },
  { id: 'lib17', name: 'EZ Bar Bicep Curl', video: 'https://www.youtube.com/watch?v=i1YgFZB6alI', desc: '' },
  { id: 'lib18', name: 'Cable Tricep Pushdown', video: 'https://www.youtube.com/watch?v=94DXwlcX8Po', desc: 'Straight bar attachment.' },
  { id: 'lib19', name: 'Cable Bicep Curls', video: 'https://www.youtube.com/watch?v=i1YgFZB6alI', desc: '' },
  { id: 'lib20', name: 'Cable Overhead Tricep Extension', video: 'https://www.youtube.com/watch?v=popGXI-qs98', desc: 'Straight bar attachment.' },
  { id: 'lib21', name: 'Prone/Seated Hamstring Curl', video: '', desc: '' },
  { id: 'lib22', name: 'Cable Ab Curls', video: '', desc: '' },
  { id: 'lib23', name: 'Parallel Bar Dips', video: '', desc: '' },
  { id: 'lib24', name: 'Incline Bench Press', video: 'https://www.youtube.com/watch?v=-iWjdKWNpNg', desc: '' },
  { id: 'lib25', name: 'Smith Machine Squat', video: '', desc: '' },
  { id: 'lib26', name: 'Hex Bar Jump', video: '', desc: '' },
  { id: 'lib27', name: 'Jump Squats', video: '', desc: '' },
  { id: 'lib28', name: 'Drop Horizontal Jump', video: '', desc: '' },
  { id: 'lib29', name: 'Barbell Push Press', video: '', desc: '' },
  { id: 'lib30', name: 'Bench Supported Side Bends', video: '', desc: '' },
  { id: 'lib31', name: 'Bent Over Anchored Cable Rotations', video: '', desc: '' },
  { id: 'lib32', name: 'Deficit Single Leg Hip Dips', video: '', desc: '' },
  { id: 'lib33', name: 'Incline Bench Garhammer Raises', video: '', desc: '' },
]

export const DEFAULT_WARMUP: ChecklistItem[] = [
  { id: 'w1', name: 'Inchworms → Pushup', target: '2 x 5' },
  { id: 'w2', name: 'Seated Calf Raises', target: '3 x 12' },
  { id: 'w3', name: 'Cable Hip Flexor Marches', target: '1 x 10 ES' },
  { id: 'w4', name: 'Isometric Leg Extensions', target: '2 x 10 sec ES' },
  { id: 'w5', name: 'Bodyweight Squat', target: '1 x 5' },
  { id: 'w6', name: 'Countermovement Jump', target: '1 x 3' },
]

export const DEFAULT_REHAB: ChecklistItem[] = [
  { id: 'r1', group: 'Stretches', name: 'Foam Roll', target: '' },
  { id: 'r2', group: 'Stretches', name: 'Calf Stretch', target: '2 x 10 ES' },
  { id: 'r3', group: 'Stretches', name: 'Quad - Sofa Stretch', target: '3 x 15 ES' },
  { id: 'r4', group: 'Stretches', name: 'Hamstring - Band Pulldowns', target: '3 x 5 ES' },
  { id: 'r5', group: 'Stretches', name: 'Hip Flexor - Split Stance Banded', target: '2 x 15 sec ES' },
  { id: 'r6', group: 'Stretches', name: 'Ankle Mobility', target: '' },
  { id: 'r7', group: 'Stretches', name: 'Banded Ankle', target: '3 x 5 ES (hold last rep 10 sec)' },
  { id: 'r8', group: 'Stretches', name: 'Hip Mobility', target: '' },
  { id: 'r9', group: 'Stretches', name: 'Banded Hip Flexor Marches', target: '2 x 10 ES' },
  { id: 'r10', group: 'Stretches', name: 'Band Distracted Spiderman', target: '3 x 5 ES' },
  { id: 'r11', group: 'Stretches', name: 'Pigeon Stretch', target: '3 x 10 sec ES' },
  { id: 'r12', group: 'Stretches', name: 'Seated 90-90 Heel Clicks', target: '3 x 5 ES' },
  { id: 'r13', group: 'Stretches', name: 'Resisted Internal Rotation', target: '3 x 5 ES' },
  { id: 'r14', group: 'Stretches', name: 'Loaded Landmine Sways', target: '3 x 5 ES' },
  { id: 'r15', group: 'Stretches', name: 'Thoracic Spine Mobility', target: '' },
  { id: 'r16', group: 'Shoulder/Hip Prehab', name: 'Split Stance Thoracic Rotation', target: '3 x 5 ES' },
  { id: 'r17', group: 'Shoulder/Hip Prehab', name: 'Shoulder Mobility', target: '' },
  { id: 'r18', group: 'Shoulder/Hip Prehab', name: 'Modified Child Pose Against Wall', target: '3 x 10 sec' },
  { id: 'r19', group: 'Shoulder/Hip Prehab', name: 'Cow Face Pose', target: '3 x 10 sec ES' },
  { id: 'r20', group: 'Shoulder/Hip Prehab', name: 'Shoulder External Rotation (Passive & Active)', target: '2 x 3 - 10 sec' },
  { id: 'r21', group: 'Shoulder/Hip Prehab', name: 'Shoulder Prehab', target: '' },
  { id: 'r22', group: 'Shoulder/Hip Prehab', name: 'Prone W Y Ts', target: '2 x 5' },
  { id: 'r23', group: 'Shoulder/Hip Prehab', name: 'Banded External Rotation', target: '2 x 5 ES' },
  { id: 'r24', group: 'Shoulder/Hip Prehab', name: 'Banded/Cable Ys', target: '2 x 5' },
  { id: 'r25', group: 'Shoulder/Hip Prehab', name: 'Lying Internal Rotation (Eccentric Focused)', target: '3 x 5 ES' },
  { id: 'r26', group: 'Shoulder/Hip Prehab', name: 'Scap Pull-Ups', target: '2 x 10' },
  { id: 'r27', group: 'Shoulder/Hip Prehab', name: 'Split Stance Upside Down KB Press', target: '2 x 5 ES' },
  { id: 'r28', group: 'Shoulder/Hip Prehab', name: 'Lower Back Prehab', target: '' },
  { id: 'r29', group: 'Shoulder/Hip Prehab', name: 'Happy Cat - Sad Cat', target: '2 x 5' },
  { id: 'r30', group: 'Shoulder/Hip Prehab', name: 'Child Pose to Prone Pressup', target: '2 x 5' },
  { id: 'r31', group: 'Shoulder/Hip Prehab', name: 'Quadruped Lift to Down Dog', target: '2 x 5' },
]
